#!/usr/bin/env python3
"""
AMFI All Cities Scraper
Scrape AMFI for ALL cities in India to maximize data collection.
AMFI API is fast and reliable - can fetch 50,000+ records quickly.
"""

import asyncio
import aiohttp
import logging
import os
import sys

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Complete list of Indian cities for AMFI scraping
AMFI_CITIES = [
    # Major Cities (Tier 1)
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Chennai",
    "Kolkata",
    "Hyderabad",
    "Pune",
    "Ahmedabad",
    "Surat",
    "Jaipur",
    # Tier 2 Cities
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Coimbatore",
    "Agra",
    "Mysore",
    "Ranchi",
    "Guwahati",
    "Chandigarh",
    "Thiruvananthapuram",
    "Srinagar",
    "Dehradun",
    "Jammu",
    "Panipat",
    "Karnal",
    "Rohtak",
    "Faridabad",
    "Gurgaon",
    "Noida",
    "Gwalior",
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Dhanbad",
    "Jamshedpur",
    "Bokaro",
    "Raipur",
    "Kolhapur",
    "Sangli",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Nanded",
    # Tier 3 Cities
    "Jalgaon",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Malegaon",
    "Warangal",
    "Karimnagar",
    "Nizamabad",
    "Khammam",
    "Rajahmundry",
    "Kakinada",
    "Nellore",
    "Anantapur",
    "Kurnool",
    "Tirupati",
    "Jabalpur",
    "Ujjain",
    "Ratlam",
    "Satna",
    "Rewa",
    "Sagar",
    "Durg",
    "Raigarh",
    "Bilaspur",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Meerut",
    "Allahabad",
    "Varanasi",
    "Mathura",
    "Jhansi",
    "Gorakhpur",
    "Faizabad",
    "Ayodhya",
    "Bhagalpur",
    "Darbhanga",
    "Muzaffarpur",
    "Gaya",
    "Purnia",
    "Katihar",
    "Bhatinda",
    "Jalandhar",
    "Patiala",
    "Sangrur",
    "Hoshiarpur",
    "Bathinda",
    "Moga",
    "Ferozepur",
    # Tier 4 - More cities
    "Kota",
    "Bhilwara",
    "Ajmer",
    "Pilani",
    "Bikaner",
    "Jodhpur",
    "Udaipur",
    "Chittorgarh",
    "Alwar",
    "Bharatpur",
    "Ganganagar",
    "Hanumangarh",
    "Pali",
    "Rajsamand",
    "Dungarpur",
    "Banswara",
    "Churu",
    "Jhunjhunu",
    "Sikar",
    "Dausa",
    "Kotputali",
    "Behror",
    "Khair",
    "Bhiwadi",
    "Rewari",
    "Gurgaon Rural",
    "Manesar",
    "Sohna",
    "Nuh",
    "Palwal",
    # West Bengal
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Berhampore",
    "Bardhaman",
    "Kharagpur",
    "Haldia",
    "Darjeeling",
    "Malda",
    "Baharampur",
    "Habra",
    "Krishnanagar",
    "Berachampa",
    "Domjur",
    "Uluberia",
    "Shibpur",
    "Naihati",
    "Khadina",
    # Karnataka
    "Bangalore",
    "Mysore",
    "Mangalore",
    "Hubli",
    "Dharwad",
    "Belgaum",
    "Bellary",
    "Tumkur",
    "Shimoga",
    "Udupi",
    "Davanagere",
    "Hassan",
    "Bidar",
    "Raichur",
    "Kolar",
    "Chitradurga",
    "Madikeri",
    "Mandya",
    "Hassan",
    "Bagalkot",
    "Bijapur",
    "Gulbarga",
    " Koppal",
    "Bellary",
    "Chitradurga",
    # Tamil Nadu
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Trichy",
    "Salem",
    "Tirunelveli",
    "Vellore",
    "Erode",
    "Tiruppur",
    "Thanjavur",
    "Nagercoil",
    "Thoothukudi",
    "Dindigul",
    "Karur",
    "Cuddalore",
    "Kanchipuram",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Kadapa",
    # Kerala
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Kannur",
    "Palakkad",
    "Alappuzha",
    "Kottayam",
    "Ernakulam",
    "Malappuram",
    "Palghat",
    "Trichur",
    "Quilon",
    "Kayamkulam",
    # Andhra Pradesh
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Nellore",
    "Kakinada",
    "Rajahmundry",
    "Kadapa",
    "Anantapur",
    "Kurnool",
    "Chittoor",
    "Eluru",
    "Ongole",
    "Srikakulam",
    "Bhimavaram",
    "Machilipatnam",
    "Hindupur",
    "Proddatur",
    "Jammalamadugu",
    "Guntakal",
    # Telangana
    "Hyderabad",
    "Warangal",
    "Karimnagar",
    "Nizamabad",
    "Khammam",
    "Ramagundam",
    "Secunderabad",
    "Adilabad",
    "Siddipet",
    "Jagtial",
    "Koratla",
    "Mancherial",
    "Bellampalle",
    "Kothakota",
    "Mahabubnagar",
    "Narayanpet",
    "Gadwal",
    "Wanaparthy",
    "Kamareddy",
    "Bhootpur",
    # Gujarat
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhidham",
    "Anand",
    "Bharuch",
    "Valsad",
    "Navsari",
    "Vapi",
    "Patan",
    "Mehsana",
    "Sabarkantha",
    "Aravalli",
    "Banaskantha",
    "Kheda",
    "Mahisagar",
    "Panchmahal",
    "Dahod",
    "Godhra",
    "Kalol",
    "Visnagar",
    # Maharashtra
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Aurangabad",
    "Kolhapur",
    "Solapur",
    "Amravati",
    "Nanded",
    "Sangli",
    "Jalgaon",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Malegaon",
    "Pune Rural",
    "Mumbai Suburban",
    "Raigad",
    "Palghar",
    "Ratnagiri",
    "Sindhudurg",
    "Kolhapur Rural",
    "Satara",
    "Sangli Rural",
    "Karad",
    "Satara Rural",
    "Phaltan",
    "Manmad",
    # Rajasthan
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Bikaner",
    "Ajmer",
    "Kota",
    "Bhilwara",
    "Pilani",
    "Chittorgarh",
    "Alwar",
    "Bharatpur",
    "Ganganagar",
    "Hanumangarh",
    "Pali",
    "Rajsamand",
    "Banswara",
    "Churu",
    "Jhunjhunu",
    "Sikar",
    "Dausa",
    "Sawai Madhopur",
    "Dungarpur",
    "Baran",
    "Jhalawar",
    "Kotputali",
    # Uttar Pradesh
    "Lucknow",
    "Kanpur",
    "Agra",
    "Varanasi",
    "Allahabad",
    "Meerut",
    "Aligarh",
    "Moradabad",
    "Bareilly",
    "Gorakhpur",
    "Mathura",
    "Jhansi",
    "Faizabad",
    "Ayodhya",
    "Ayodhya",
    "Ghaziabad",
    "Noida",
    "Greater Noida",
    "Saharanpur",
    "Muzaffarnagar",
    "Shahjahanpur",
    "Lakhimpur",
    "Sitapur",
    "Hardoi",
    "Unnao",
    "Rae Bareli",
    "Pratapgarh",
    "Azamgarh",
    "Mau",
    "Ballia",
    # Madhya Pradesh
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Satna",
    "Rewa",
    "Sagar",
    "Dewas",
    "Ratlam",
    "Burhanpur",
    "Khandwa",
    "Khargone",
    "Mandsaur",
    "Neemuch",
    "Chhindwara",
    "Sehore",
    "Raisen",
    "Rajgarh",
    "Vidisha",
    "Betul",
    "Ashoknagar",
    "Shivpuri",
    "Guna",
    "Bhind",
    # Bihar
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Katihar",
    "Bihar Sharif",
    "Arrah",
    "Buxar",
    "Koch",
    "Hajipur",
    "Samastipur",
    "Saran",
    "Siwan",
    "Gopalganj",
    "Madhubani",
    "Supaul",
    "Madhepura",
    "Saharsa",
    "Khagaria",
    "Munger",
    "Lakhisarai",
    "Sheikhpura",
    "Nalanda",
    # Punjab
    "Chandigarh",
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Hoshiarpur",
    "Moga",
    "Ferozepur",
    "Sangrur",
    "Pathankot",
    "Phagwara",
    "Kapurthala",
    "Nawanshahr",
    "Muktsar",
    "Fatehgarh Sahib",
    "Ropar",
    "Mohali",
    "Zirakpur",
    "Kharar",
    # Haryana
    "Faridabad",
    "Gurgaon",
    "Panipat",
    "Karnal",
    "Rohtak",
    "Hisar",
    "Sonipat",
    "Rewari",
    "Jhajjar",
    "Mahipalpur",
    "Palwal",
    "Nuh",
    "Bhiwadi",
    "Gurugram",
    "Manesar",
    "Sohna",
    "Tapukda",
    "Kundli",
    "Sector",
    "Yamunanagar",
    "Kurukshetra",
    "Kaithal",
    "Jind",
    "Sirsa",
    "Fatehabad",
    # Uttarakhand
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Rishikesh",
    "Haldwani",
    "Nainital",
    "Almora",
    "Kashipur",
    "Rudrapur",
    "Kotdwar",
    "Ramnagar",
    "Mussoorie",
    "Chakrata",
    "Tehri",
    "Uttarkashi",
    # Odisha
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Balasore",
    "Bhadrak",
    "Puri",
    "Konark",
    "Kalahandi",
    "Kandhamal",
    "Ganjam",
    "Gajapati",
    "Koraput",
    "Malkangiri",
    "Rayagada",
    "Kalahandi",
    "Nabarangpur",
    "Balangir",
    "Sonepur",
    # Jharkhand
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Hazaribagh",
    "Deoghar",
    "Phusro",
    "Giridih",
    "Ramgarh",
    "Chaibasa",
    "Gumla",
    "Simdega",
    "Koderma",
    "Chatra",
    "Latehar",
    # Chhattisgarh
    "Raipur",
    "Bhilai",
    "Durg",
    "Bilaspur",
    "Korba",
    "Rajnandgaon",
    "Raigarh",
    "Janjgir",
    "Mahasamund",
    "Dhamtari",
    "Kanker",
    "Bastar",
    "Sarguja",
    "Kabirdham",
    "Koriya",
    # Northeast
    "Guwahati",
    "Shillong",
    "Imphal",
    "Agartala",
    "Aizawl",
    "Kohima",
    "Itanagar",
    "Gangtok",
    "Dibrugarh",
    "Tinsukia",
    "Jorhat",
    "Silchar",
    "Dimapur",
    "Tuensang",
    "Kohima",
    # Union Territories
    "Chandigarh",
    "Puducherry",
    "Delhi",
    "Jammu",
    "Srinagar",
    "Lakshadweep",
    "Andaman",
    "Nicobar",
    "Dadra",
    "Daman",
]

# Remove duplicates while preserving order
AMFI_CITIES = list(dict.fromkeys(AMFI_CITIES))

AMFI_API_URL = "https://www.amfiindia.com/api/distributor-agent"


async def scrape_amfi_city(session: aiohttp.ClientSession, city: str) -> dict:
    """Scrape AMFI for a single city."""
    results = {"city": city, "count": 0, "records": [], "error": None}

    try:
        params = {"strOpt": "ALL", "city": city, "page": 1, "pageSize": 10000}
        async with session.get(
            AMFI_API_URL, params=params, timeout=aiohttp.ClientTimeout(total=30)
        ) as resp:
            if resp.status == 200:
                data = await resp.json(content_type=None)
                records = data.get("data", [])
                results["records"] = records
                results["count"] = len(records)
            else:
                results["error"] = f"HTTP {resp.status}"
    except Exception as e:
        results["error"] = str(e)

    return results


async def scrape_all_amfi_cities():
    """Scrape AMFI for all cities in parallel."""

    connector = aiohttp.TCPConnector(limit=10)
    timeout = aiohttp.ClientTimeout(total=30)

    async with aiohttp.ClientSession(
        connector=connector, timeout=timeout, headers={"User-Agent": "Mozilla/5.0"}
    ) as session:
        total = 0
        failed = 0

        # Process in batches of 10
        for i in range(0, len(AMFI_CITIES), 10):
            batch = AMFI_CITIES[i : i + 10]
            tasks = [scrape_amfi_city(session, city) for city in batch]
            results = await asyncio.gather(*tasks)

            for r in results:
                if r["count"] > 0:
                    total += r["count"]
                    logger.info(f"✓ {r['city']}: {r['count']} records")
                else:
                    failed += 1
                    if r["error"]:
                        logger.warning(f"✗ {r['city']}: {r['error']}")

            logger.info(
                f"Progress: {i + len(batch)}/{len(AMFI_CITIES)} cities, Total: {total}"
            )

        logger.info(f"\n=== AMFI SCRAPING COMPLETE ===")
        logger.info(f"Total records: {total}")
        logger.info(f"Failed cities: {failed}")

        return total


if __name__ == "__main__":
    asyncio.run(scrape_all_amfi_cities())
